### ISSUE TITLE
[ERROR] 'list' object has no attribute 'chat' error after upgrading 0.2.0 -> 0.2.2

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#33]
Hello. After upgrading from 0.2.0 to 0.2.2 I'm facing the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/telebot/__init__.py", line 39, in run
    task(*args, **kwargs)
  File "./bashbot.py", line 13, in listener
    chatid = m.chat.id
AttributeError: 'list' object has no attribute 'chat'
```

piece of code, where error happens (error in 3rd line here):
```python
def listener(*messages):
    for m in messages:
        chatid = m.chat.id
        if m.content_type == 'text' and m.text.startswith('/bash'):
            tb.send_message(chatid, bash.getQuote())
            parse_stats.update_analytics(chatid, 'bash')
```
The code in README (Echo bot) doesn't work any longer in 0.2.2, hovewer after reverting to 0.2.0 it works.
What's even worse, I can't find the commit which breaks it all...

**Comment by GabrielRF** [comment]
Try removing the * from the listener.
```
def listener(messages):
    for m in messages:
```

**Comment by Kondra007** [comment]
@GabrielRF Thank you! I didn't see the difference in this asterisk :(
