### ISSUE TITLE
How to Use SOCKS5 proxy?

### ISSUE THREAD

**Issue by LeoNeeDpk1** [eternnoir/pyTelegramBotAPI#493]
1. What version of pyTelegramBotAPI are you using?
3.5.2

2. What OS are you using?
Linux Mint

3. What version of python are you using?
3.5.2
**==========**

Hi. I did everything that described in Readme, but it seems that

```
proxies = {
'http': 'socks5://telegram.vpn99.net:55655',
'https': 'socks5://telegram.vpn99.net:55655'
}
```
, pasted at the beggining of the script, has no effect.
Bot does not use them.
What am I doing wrong?

Thank you for response.

**Comment by LeoNeeDpk1** [comment]
```
from telebot import apihelper
apihelper.proxy = {'https': 'socks5://telegram.vpn99.net:55655'}
```
raise Not supported proxy scheme socks5

```
from telebot import apihelper
apihelper.proxies = {'https': 'socks5://telegram.vpn99.net:55655'}
```
does nothing at all. Script just ignores that proxy, you can put anything in _{}_ field but without any result.

**Comment by Nicknk** [comment]
@LeoNeeDpk1, i have solved problem with using proxy by install pysocks into the enviroment.
In code i have next rows:
`from telebot import apihelper`
`apihelper.proxy = {'https': 'socks5://userproxy:password@ams3.proxy.veesecurity.com:443'}`

**Comment by Nicknk** [comment]
@LeoNeeDpk1 , I am sorry, but I haven't done something other.
I have next version of some modules, that can be related to this problem:
`gunicorn (19.7.1) 
PySocks (1.6.8)
pyTelegramBotAPI (3.6.2)
requests (2.18.4)
urllib3 (1.22)`

**Comment by khabibr** [comment]
sudo pip3 install requests[socks]
------------- apihelper.py ------------
def download_file(token, file_path):
    url = FILE_URL.format(token, file_path)
    # result = _get_req_session().get(url)
    result = _get_req_session().get(url**, proxies=proxy**)
    if result.status_code != 200:
        msg = 'The server returned HTTP {0} {1}. Response body:\n[{2}]' \
            .format(result.status_code, result.reason, result.text)
        raise ApiException(msg, 'Download file', result)
    return result.content

**Comment by LeoNeeDpk1** [comment]
@Nicknk 
Dude! You are ewesome!
I had outdated **requests** lib.
Now everything works. Thank you!

Issue can be closed.

Btw, may be we need to refresh a readme about SOCKS5 proxy?

**Comment by LeoNeeDpk1** [comment]
#494

**Comment by LeoNeeDpk1** [comment]
request for readme update
#494

**Comment by RandyRomero** [comment]
@khabibr Could you please do a pull request with this improved function of yours?

**Comment by khabibr** [comment]
[Pull request done](https://github.com/eternnoir/pyTelegramBotAPI/pull/497)
<Russian> Привет Россиянам :) </Russian>

**Comment by khabibr** [comment]
Done

2018-04-24 11:50 GMT+06:00 Aleksandr Mikheev <notifications@github.com>:

**Comment by RandyRomero** [comment]
@khabibr thank you) Yeah, that ban of Telegram in Russia is really annoying.

**Comment by IT-KOT** [comment]
Доброго времени суток как только не пытался....
Всё сделал по инструкции https://pastebin.com/McT48zuq
Но выбрасывает ошибку: https://pastebin.com/QrNhcYrv
Вообщем проблема в соединение, поэтому добавленны следующие строки: from telebot import apihelper

apihelper.proxy = {'https': 'socks5://47.75.31.98:1080'}
но всё равно выбрасывает ошибку, подскажите что нужно сделать? может socks5 не рабочий, хотя пробывал другие подключать, кто сталкивался?
Это простой echo bot , подскажите что мне и где в коде нужно прописать чтобы заработало?

**Comment by chippp** [comment]
Лучше поздно чем никогда )
версия requests должна быть 2.10.0, иначе ошибка SSLError

**Comment by andy-ye** [comment]
> Лучше поздно чем никогда ) При ошибке (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:749)'),))
> 
> 1. Downgrade requests до версии 2.10.0
>    или
> 2. В URL-адресе прокси-сервера сменить socks5 на socks5h

Thanks chippp! Changing to socks5h is working!

**Comment by chebotarevmichael** [comment]
> Лучше поздно чем никогда ) При ошибке (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:749)'),))
> 
> 1. Downgrade requests до версии 2.10.0
>    или
> 2. В URL-адресе прокси-сервера сменить socks5 на socks5h

Спасибо огромное!) It hepled me!

**Comment by adtsvetkov** [comment]
Frien

> Лучше поздно чем никогда ) При ошибке (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:749)'),))
> 
> 1. Downgrade requests до версии 2.10.0
>    или
> 2. В URL-адресе прокси-сервера сменить socks5 на socks5h

maybe you know what to do with this error:
`(util.py:66 PollingThread) ERROR - TeleBot: "AttributeError occurred, args=("'NoneType' object has no attribute 'format'",)`
can it be related to bad proxy?
gunicorn, PySocks, pyTelegramBotAPI, requests, urllib3 latest versions are installed.
IDE: PyCharm 3.0.3
Python 3.7.4
Thank you!
