### PR TITLE
fixing escape()

### PR DESCRIPTION
**Pull request by reddere**
fixing escape() as replacing a None would throw an exception 'NoneType' object has no attribute 'replace'. useful in case of escaping a None string given from message.from_user.last_name as you dont know wether the user has a last name or not

### CODE REVIEW

**Comment by Badiboy** [comment]
Suitable update.

Please:
`if text == None:`
Bad practice. Replace to
`if text is None:`

And "else" after that not needed.

**Comment by reddere** [comment]
thanks! changed the "== None" to "is None", what do you mean by "And "else" after that not needed."?

**Comment by reddere** [comment]
should be fine now, let me know if any more changes are needed!

**Comment by Badiboy** [comment]
👍
